version: "3.9"

services:
  app:
    build: .
    ports:
      - "5002:8080"
    environment:
      PORT: 8080
      REDIS_URL: "redis:6379"
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
